### ISSUE TITLE
Identity provider configuration has some naming inconsistency

### ISSUE THREAD

**Issue by jometzner** [intershop/intershop-pwa#1274]
**Actual Behavior**

As per `configuration.effects.ts` the way to select the used identity provider out of the set of configured providers is `ICM_IDENTITY_PROVIDER` environment variable.

For instance out of two configured identity providers, I have to set above mentioned env variable.
```yaml
      ICM_IDENTITY_PROVIDER: 'AUTH0'
      IDENTITY_PROVIDERS: |
        PUNCHOUT:
          type: PUNCHOUT
        AUTH0:
          type: 'auth0'
          domain: 'xxxx'
          clientID: 'yyyy'
```

**Expected Behavior**

I'd like to have consistent naming
```yaml
      IDENTITY_PROVIDER: 'AUTH0'
      IDENTITY_PROVIDERS: |
        PUNCHOUT:
          type: PUNCHOUT
        AUTH0:
          type: 'auth0'
          domain: 'xxxx'
          clientID: 'yyyy'
```

[AB#79613](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/79613)
